// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/usecase/contracts.go
//
// Generated by this command:
//
//	mockgen -source ./internal/usecase/contracts.go -destination ./internal/usecase/mocks_usecase_test.go -package usecase_test
//

// Package usecase_test is a generated GoMock package.
package usecase_test

import (
	entity "adoptme/internal/entity"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockShelter is a mock of Shelter interface.
type MockShelter struct {
	ctrl     *gomock.Controller
	recorder *MockShelterMockRecorder
	isgomock struct{}
}

// MockShelterMockRecorder is the mock recorder for MockShelter.
type MockShelterMockRecorder struct {
	mock *MockShelter
}

// NewMockShelter creates a new mock instance.
func NewMockShelter(ctrl *gomock.Controller) *MockShelter {
	mock := &MockShelter{ctrl: ctrl}
	mock.recorder = &MockShelterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShelter) EXPECT() *MockShelterMockRecorder {
	return m.recorder
}

// Login mocks base method.
func (m *MockShelter) Login(ctx context.Context, email, password string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, email, password)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockShelterMockRecorder) Login(ctx, email, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockShelter)(nil).Login), ctx, email, password)
}

// Register mocks base method.
func (m *MockShelter) Register(ctx context.Context, name, email, password string) (entity.Shelter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", ctx, name, email, password)
	ret0, _ := ret[0].(entity.Shelter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Register indicates an expected call of Register.
func (mr *MockShelterMockRecorder) Register(ctx, name, email, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockShelter)(nil).Register), ctx, name, email, password)
}

// MockVolunteer is a mock of Volunteer interface.
type MockVolunteer struct {
	ctrl     *gomock.Controller
	recorder *MockVolunteerMockRecorder
	isgomock struct{}
}

// MockVolunteerMockRecorder is the mock recorder for MockVolunteer.
type MockVolunteerMockRecorder struct {
	mock *MockVolunteer
}

// NewMockVolunteer creates a new mock instance.
func NewMockVolunteer(ctrl *gomock.Controller) *MockVolunteer {
	mock := &MockVolunteer{ctrl: ctrl}
	mock.recorder = &MockVolunteerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVolunteer) EXPECT() *MockVolunteerMockRecorder {
	return m.recorder
}

// Login mocks base method.
func (m *MockVolunteer) Login(ctx context.Context, email, password string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, email, password)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockVolunteerMockRecorder) Login(ctx, email, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockVolunteer)(nil).Login), ctx, email, password)
}

// Register mocks base method.
func (m *MockVolunteer) Register(ctx context.Context, name, email, password string) (entity.Volunteer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", ctx, name, email, password)
	ret0, _ := ret[0].(entity.Volunteer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Register indicates an expected call of Register.
func (mr *MockVolunteerMockRecorder) Register(ctx, name, email, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockVolunteer)(nil).Register), ctx, name, email, password)
}

// MockCatalog is a mock of Catalog interface.
type MockCatalog struct {
	ctrl     *gomock.Controller
	recorder *MockCatalogMockRecorder
	isgomock struct{}
}

// MockCatalogMockRecorder is the mock recorder for MockCatalog.
type MockCatalogMockRecorder struct {
	mock *MockCatalog
}

// NewMockCatalog creates a new mock instance.
func NewMockCatalog(ctrl *gomock.Controller) *MockCatalog {
	mock := &MockCatalog{ctrl: ctrl}
	mock.recorder = &MockCatalogMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCatalog) EXPECT() *MockCatalogMockRecorder {
	return m.recorder
}

// ListAnimal mocks base method.
func (m *MockCatalog) ListAnimal(ctx context.Context) ([]entity.Animal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAnimal", ctx)
	ret0, _ := ret[0].([]entity.Animal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAnimal indicates an expected call of ListAnimal.
func (mr *MockCatalogMockRecorder) ListAnimal(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAnimal", reflect.TypeOf((*MockCatalog)(nil).ListAnimal), ctx)
}

// ListShelters mocks base method.
func (m *MockCatalog) ListShelters(ctx context.Context) ([]entity.Shelter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListShelters", ctx)
	ret0, _ := ret[0].([]entity.Shelter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListShelters indicates an expected call of ListShelters.
func (mr *MockCatalogMockRecorder) ListShelters(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListShelters", reflect.TypeOf((*MockCatalog)(nil).ListShelters), ctx)
}

// ListVolunteer mocks base method.
func (m *MockCatalog) ListVolunteer(ctx context.Context) ([]entity.Volunteer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListVolunteer", ctx)
	ret0, _ := ret[0].([]entity.Volunteer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListVolunteer indicates an expected call of ListVolunteer.
func (mr *MockCatalogMockRecorder) ListVolunteer(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListVolunteer", reflect.TypeOf((*MockCatalog)(nil).ListVolunteer), ctx)
}

// MockAdoption is a mock of Adoption interface.
type MockAdoption struct {
	ctrl     *gomock.Controller
	recorder *MockAdoptionMockRecorder
	isgomock struct{}
}

// MockAdoptionMockRecorder is the mock recorder for MockAdoption.
type MockAdoptionMockRecorder struct {
	mock *MockAdoption
}

// NewMockAdoption creates a new mock instance.
func NewMockAdoption(ctrl *gomock.Controller) *MockAdoption {
	mock := &MockAdoption{ctrl: ctrl}
	mock.recorder = &MockAdoptionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdoption) EXPECT() *MockAdoptionMockRecorder {
	return m.recorder
}

// RegisterAnimal mocks base method.
func (m *MockAdoption) RegisterAnimal(ctx context.Context, name, ownerId string, ownerType entity.OwnerType) (entity.Animal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterAnimal", ctx, name, ownerId, ownerType)
	ret0, _ := ret[0].(entity.Animal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegisterAnimal indicates an expected call of RegisterAnimal.
func (mr *MockAdoptionMockRecorder) RegisterAnimal(ctx, name, ownerId, ownerType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterAnimal", reflect.TypeOf((*MockAdoption)(nil).RegisterAnimal), ctx, name, ownerId, ownerType)
}

// TransferAnimal mocks base method.
func (m *MockAdoption) TransferAnimal(ctx context.Context, animalID, newOwnerID string, newOwnerType entity.OwnerType) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TransferAnimal", ctx, animalID, newOwnerID, newOwnerType)
	ret0, _ := ret[0].(error)
	return ret0
}

// TransferAnimal indicates an expected call of TransferAnimal.
func (mr *MockAdoptionMockRecorder) TransferAnimal(ctx, animalID, newOwnerID, newOwnerType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TransferAnimal", reflect.TypeOf((*MockAdoption)(nil).TransferAnimal), ctx, animalID, newOwnerID, newOwnerType)
}
