// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/usecase/contracts.go
//
// Generated by this command:
//
//	mockgen -source ./internal/usecase/contracts.go -destination ./internal/usecase/mocks_usecase_test.go -package usecase_test
//

// Package usecase_test is a generated GoMock package.
package usecase_test

import (
	entity "adoptme/internal/entity"
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockUser is a mock of User interface.
type MockUser struct {
	ctrl     *gomock.Controller
	recorder *MockUserMockRecorder
	isgomock struct{}
}

// MockUserMockRecorder is the mock recorder for MockUser.
type MockUserMockRecorder struct {
	mock *MockUser
}

// NewMockUser creates a new mock instance.
func NewMockUser(ctrl *gomock.Controller) *MockUser {
	mock := &MockUser{ctrl: ctrl}
	mock.recorder = &MockUserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUser) EXPECT() *MockUserMockRecorder {
	return m.recorder
}

// RegisterShelter mocks base method.
func (m *MockUser) RegisterShelter(arg0 context.Context, arg1 entity.Shelter) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterShelter", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterShelter indicates an expected call of RegisterShelter.
func (mr *MockUserMockRecorder) RegisterShelter(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterShelter", reflect.TypeOf((*MockUser)(nil).RegisterShelter), arg0, arg1)
}

// RegisterVolunteer mocks base method.
func (m *MockUser) RegisterVolunteer(arg0 context.Context, arg1 entity.Volunteer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterVolunteer", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterVolunteer indicates an expected call of RegisterVolunteer.
func (mr *MockUserMockRecorder) RegisterVolunteer(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterVolunteer", reflect.TypeOf((*MockUser)(nil).RegisterVolunteer), arg0, arg1)
}

// MockCatalog is a mock of Catalog interface.
type MockCatalog struct {
	ctrl     *gomock.Controller
	recorder *MockCatalogMockRecorder
	isgomock struct{}
}

// MockCatalogMockRecorder is the mock recorder for MockCatalog.
type MockCatalogMockRecorder struct {
	mock *MockCatalog
}

// NewMockCatalog creates a new mock instance.
func NewMockCatalog(ctrl *gomock.Controller) *MockCatalog {
	mock := &MockCatalog{ctrl: ctrl}
	mock.recorder = &MockCatalogMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCatalog) EXPECT() *MockCatalogMockRecorder {
	return m.recorder
}

// ListShelters mocks base method.
func (m *MockCatalog) ListShelters(arg0 context.Context) ([]entity.Shelter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListShelters", arg0)
	ret0, _ := ret[0].([]entity.Shelter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListShelters indicates an expected call of ListShelters.
func (mr *MockCatalogMockRecorder) ListShelters(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListShelters", reflect.TypeOf((*MockCatalog)(nil).ListShelters), arg0)
}

// ListVolunteer mocks base method.
func (m *MockCatalog) ListVolunteer(arg0 context.Context) ([]entity.Volunteer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListVolunteer", arg0)
	ret0, _ := ret[0].([]entity.Volunteer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListVolunteer indicates an expected call of ListVolunteer.
func (mr *MockCatalogMockRecorder) ListVolunteer(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListVolunteer", reflect.TypeOf((*MockCatalog)(nil).ListVolunteer), arg0)
}

// MockAdoption is a mock of Adoption interface.
type MockAdoption struct {
	ctrl     *gomock.Controller
	recorder *MockAdoptionMockRecorder
	isgomock struct{}
}

// MockAdoptionMockRecorder is the mock recorder for MockAdoption.
type MockAdoptionMockRecorder struct {
	mock *MockAdoption
}

// NewMockAdoption creates a new mock instance.
func NewMockAdoption(ctrl *gomock.Controller) *MockAdoption {
	mock := &MockAdoption{ctrl: ctrl}
	mock.recorder = &MockAdoptionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdoption) EXPECT() *MockAdoptionMockRecorder {
	return m.recorder
}

// RegisterAnimal mocks base method.
func (m *MockAdoption) RegisterAnimal(arg0 context.Context, arg1 entity.Animal) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterAnimal", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterAnimal indicates an expected call of RegisterAnimal.
func (mr *MockAdoptionMockRecorder) RegisterAnimal(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterAnimal", reflect.TypeOf((*MockAdoption)(nil).RegisterAnimal), arg0, arg1)
}

// TransferAnimal mocks base method.
func (m *MockAdoption) TransferAnimal(ctx context.Context, animalID, newOwnerID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TransferAnimal", ctx, animalID, newOwnerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// TransferAnimal indicates an expected call of TransferAnimal.
func (mr *MockAdoptionMockRecorder) TransferAnimal(ctx, animalID, newOwnerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TransferAnimal", reflect.TypeOf((*MockAdoption)(nil).TransferAnimal), ctx, animalID, newOwnerID)
}
