// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/repo/contracts.go
//
// Generated by this command:
//
//	mockgen -source ./internal/repo/contracts.go -destination ./internal/usecase/mocks_repo_test.go -package usecase_test
//

// Package usecase_test is a generated GoMock package.
package usecase_test

import (
	entity "adoptme/internal/entity"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockShelterRepo is a mock of ShelterRepo interface.
type MockShelterRepo struct {
	ctrl     *gomock.Controller
	recorder *MockShelterRepoMockRecorder
	isgomock struct{}
}

// MockShelterRepoMockRecorder is the mock recorder for MockShelterRepo.
type MockShelterRepoMockRecorder struct {
	mock *MockShelterRepo
}

// NewMockShelterRepo creates a new mock instance.
func NewMockShelterRepo(ctrl *gomock.Controller) *MockShelterRepo {
	mock := &MockShelterRepo{ctrl: ctrl}
	mock.recorder = &MockShelterRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShelterRepo) EXPECT() *MockShelterRepoMockRecorder {
	return m.recorder
}

// GetByEmail mocks base method.
func (m *MockShelterRepo) GetByEmail(ctx context.Context, email string) (entity.Shelter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmail", ctx, email)
	ret0, _ := ret[0].(entity.Shelter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmail indicates an expected call of GetByEmail.
func (mr *MockShelterRepoMockRecorder) GetByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmail", reflect.TypeOf((*MockShelterRepo)(nil).GetByEmail), ctx, email)
}

// GetByID mocks base method.
func (m *MockShelterRepo) GetByID(ctx context.Context, id string) (entity.Shelter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(entity.Shelter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockShelterRepoMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockShelterRepo)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockShelterRepo) List(ctx context.Context) ([]entity.Shelter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]entity.Shelter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockShelterRepoMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockShelterRepo)(nil).List), ctx)
}

// Store mocks base method.
func (m *MockShelterRepo) Store(ctx context.Context, sh *entity.Shelter) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", ctx, sh)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockShelterRepoMockRecorder) Store(ctx, sh any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockShelterRepo)(nil).Store), ctx, sh)
}

// MockVolunteerRepo is a mock of VolunteerRepo interface.
type MockVolunteerRepo struct {
	ctrl     *gomock.Controller
	recorder *MockVolunteerRepoMockRecorder
	isgomock struct{}
}

// MockVolunteerRepoMockRecorder is the mock recorder for MockVolunteerRepo.
type MockVolunteerRepoMockRecorder struct {
	mock *MockVolunteerRepo
}

// NewMockVolunteerRepo creates a new mock instance.
func NewMockVolunteerRepo(ctrl *gomock.Controller) *MockVolunteerRepo {
	mock := &MockVolunteerRepo{ctrl: ctrl}
	mock.recorder = &MockVolunteerRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVolunteerRepo) EXPECT() *MockVolunteerRepoMockRecorder {
	return m.recorder
}

// GetByEmail mocks base method.
func (m *MockVolunteerRepo) GetByEmail(ctx context.Context, email string) (entity.Volunteer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmail", ctx, email)
	ret0, _ := ret[0].(entity.Volunteer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmail indicates an expected call of GetByEmail.
func (mr *MockVolunteerRepoMockRecorder) GetByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmail", reflect.TypeOf((*MockVolunteerRepo)(nil).GetByEmail), ctx, email)
}

// GetByID mocks base method.
func (m *MockVolunteerRepo) GetByID(ctx context.Context, id string) (entity.Volunteer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(entity.Volunteer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockVolunteerRepoMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockVolunteerRepo)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockVolunteerRepo) List(ctx context.Context) ([]entity.Volunteer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]entity.Volunteer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockVolunteerRepoMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockVolunteerRepo)(nil).List), ctx)
}

// Store mocks base method.
func (m *MockVolunteerRepo) Store(ctx context.Context, vl *entity.Volunteer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", ctx, vl)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockVolunteerRepoMockRecorder) Store(ctx, vl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockVolunteerRepo)(nil).Store), ctx, vl)
}

// MockAnimalRepo is a mock of AnimalRepo interface.
type MockAnimalRepo struct {
	ctrl     *gomock.Controller
	recorder *MockAnimalRepoMockRecorder
	isgomock struct{}
}

// MockAnimalRepoMockRecorder is the mock recorder for MockAnimalRepo.
type MockAnimalRepoMockRecorder struct {
	mock *MockAnimalRepo
}

// NewMockAnimalRepo creates a new mock instance.
func NewMockAnimalRepo(ctrl *gomock.Controller) *MockAnimalRepo {
	mock := &MockAnimalRepo{ctrl: ctrl}
	mock.recorder = &MockAnimalRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAnimalRepo) EXPECT() *MockAnimalRepoMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockAnimalRepo) GetByID(ctx context.Context, id string) (entity.Animal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(entity.Animal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockAnimalRepoMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockAnimalRepo)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockAnimalRepo) List(ctx context.Context) ([]entity.Animal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]entity.Animal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockAnimalRepoMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockAnimalRepo)(nil).List), ctx)
}

// Store mocks base method.
func (m *MockAnimalRepo) Store(ctx context.Context, an *entity.Animal) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", ctx, an)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockAnimalRepoMockRecorder) Store(ctx, an any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockAnimalRepo)(nil).Store), ctx, an)
}

// UpdateOwner mocks base method.
func (m *MockAnimalRepo) UpdateOwner(ctx context.Context, animalID, ownerID string, ownerType entity.OwnerType) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOwner", ctx, animalID, ownerID, ownerType)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOwner indicates an expected call of UpdateOwner.
func (mr *MockAnimalRepoMockRecorder) UpdateOwner(ctx, animalID, ownerID, ownerType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOwner", reflect.TypeOf((*MockAnimalRepo)(nil).UpdateOwner), ctx, animalID, ownerID, ownerType)
}
