// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/repo/contracts.go
//
// Generated by this command:
//
//	mockgen -source ./internal/repo/contracts.go -destination ./internal/usecase/mocks_repo_test.go -package usecase_test
//

// Package usecase_test is a generated GoMock package.
package usecase_test

import (
	entity "adoptme/internal/entity"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockShelterRepo is a mock of ShelterRepo interface.
type MockShelterRepo struct {
	ctrl     *gomock.Controller
	recorder *MockShelterRepoMockRecorder
	isgomock struct{}
}

// MockShelterRepoMockRecorder is the mock recorder for MockShelterRepo.
type MockShelterRepoMockRecorder struct {
	mock *MockShelterRepo
}

// NewMockShelterRepo creates a new mock instance.
func NewMockShelterRepo(ctrl *gomock.Controller) *MockShelterRepo {
	mock := &MockShelterRepo{ctrl: ctrl}
	mock.recorder = &MockShelterRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShelterRepo) EXPECT() *MockShelterRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockShelterRepo) Create(arg0 context.Context, arg1 entity.Shelter) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockShelterRepoMockRecorder) Create(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockShelterRepo)(nil).Create), arg0, arg1)
}

// GetArray mocks base method.
func (m *MockShelterRepo) GetArray(arg0 context.Context) ([]entity.Shelter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetArray", arg0)
	ret0, _ := ret[0].([]entity.Shelter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetArray indicates an expected call of GetArray.
func (mr *MockShelterRepoMockRecorder) GetArray(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetArray", reflect.TypeOf((*MockShelterRepo)(nil).GetArray), arg0)
}

// MockVolunteerRepo is a mock of VolunteerRepo interface.
type MockVolunteerRepo struct {
	ctrl     *gomock.Controller
	recorder *MockVolunteerRepoMockRecorder
	isgomock struct{}
}

// MockVolunteerRepoMockRecorder is the mock recorder for MockVolunteerRepo.
type MockVolunteerRepoMockRecorder struct {
	mock *MockVolunteerRepo
}

// NewMockVolunteerRepo creates a new mock instance.
func NewMockVolunteerRepo(ctrl *gomock.Controller) *MockVolunteerRepo {
	mock := &MockVolunteerRepo{ctrl: ctrl}
	mock.recorder = &MockVolunteerRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVolunteerRepo) EXPECT() *MockVolunteerRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockVolunteerRepo) Create(arg0 context.Context, arg1 entity.Volunteer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockVolunteerRepoMockRecorder) Create(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockVolunteerRepo)(nil).Create), arg0, arg1)
}

// GetArray mocks base method.
func (m *MockVolunteerRepo) GetArray(arg0 context.Context) ([]entity.Volunteer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetArray", arg0)
	ret0, _ := ret[0].([]entity.Volunteer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetArray indicates an expected call of GetArray.
func (mr *MockVolunteerRepoMockRecorder) GetArray(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetArray", reflect.TypeOf((*MockVolunteerRepo)(nil).GetArray), arg0)
}

// MockAnimalRepo is a mock of AnimalRepo interface.
type MockAnimalRepo struct {
	ctrl     *gomock.Controller
	recorder *MockAnimalRepoMockRecorder
	isgomock struct{}
}

// MockAnimalRepoMockRecorder is the mock recorder for MockAnimalRepo.
type MockAnimalRepoMockRecorder struct {
	mock *MockAnimalRepo
}

// NewMockAnimalRepo creates a new mock instance.
func NewMockAnimalRepo(ctrl *gomock.Controller) *MockAnimalRepo {
	mock := &MockAnimalRepo{ctrl: ctrl}
	mock.recorder = &MockAnimalRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAnimalRepo) EXPECT() *MockAnimalRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAnimalRepo) Create(arg0 context.Context, arg1 entity.Animal) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockAnimalRepoMockRecorder) Create(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAnimalRepo)(nil).Create), arg0, arg1)
}

// UpdateOwner mocks base method.
func (m *MockAnimalRepo) UpdateOwner(arg0 context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UpdateOwner", arg0)
}

// UpdateOwner indicates an expected call of UpdateOwner.
func (mr *MockAnimalRepoMockRecorder) UpdateOwner(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOwner", reflect.TypeOf((*MockAnimalRepo)(nil).UpdateOwner), arg0)
}
